### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: SOCNN.pkl

### ISSUE THREAD

**Issue by petteriTeikari** [mbinkowski/nntimeseries#1]
Thanks for sharing the code @mbinkowski of your interesting paper. However I had some issues trying to make the model run for the household data

For example, I got the following:

```python
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/petteri/anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 56, in try_read
    with open(path, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/petteri/Dropbox/Data/nntimeseries/results/household_SOCNN.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nntimeseries/nnts/models/SOCNN.py", line 158, in <module>
    runner.run(SOCNNmodel, limit=1)
  File "nntimeseries/nnts/utils.py", line 110, in run
    self.cresults = self._read_results()
  File "/nntimeseries/nnts/utils.py", line 64, in _read_results
    results = [v for k, v in pd.read_pickle(self.save_file).T.to_dict().items()]
  File "anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 68, in read_pickle
    return try_read(path, encoding='latin1')
  File "anaconda3/lib/python3.6/site-packages/pandas/io/pickle.py", line 61, in try_read
    with open(path, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/Data/nntimeseries/results/household_SOCNN.pkl'
```
And on line 110 of `utils.py`, there is an attempt to read some results from pickled file that I don't have as I have never run the model yet successfully?

I replaced that with empty dictionary: `self.cresults = {}`, and had to add `WDIR` manually to some files, and then hit that when putting `limit` higher than 1:

```python
using <class '__main__.SOCNNmodel'> to build the model
using <class 'nnts.household.HouseholdGenerator'> to draw samples
Traceback (most recent call last):
  File "nntimeseries/nnts/models/SOCNN.py", line 159, in <module>
    runner.run(SOCNNmodel, log=log, limit=6)
  File "nntimeseries/nnts/utils.py", line 150, in run
    model = model_class(data, params, os.path.join(WDIR, 'tensorboard'))
  File "nntimeseries/nnts/utils.py", line 263, in __init__
    self.nn, self.io_func, self.callbacks = self.build()
  File "nntimeseries/nnts/models/SOCNN.py", line 136, in build
    out = outL(main)
  File "anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 578, in __call__
    output = self.call(inputs, **kwargs)
  File "anaconda3/lib/python3.6/site-packages/keras/layers/local.py", line 159, in call
    x_aggregate = K.concatenate(xs, axis=0)
  File "anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1553, in concatenate
    return tf.sparse_concat(axis, tensors)
  File "anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/sparse_ops.py", line 227, in sparse_concat
    inds, vals, shapes, axis, name=name))
  File "anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_sparse_ops.py", line 428, in _sparse_concat
    concat_dim=concat_dim, name=name)
  File "anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 546, in apply_op
    (input_name, op_type_name, len(values), num_attr.minimum))
ValueError: List argument 'indices' to 'SparseConcat' Op with length 0 shorter than minimum length 2.
```
Any idea of the errors?

**Comment by petteriTeikari** [comment]
There was a typo also on line 159 of `SOCNN.py` when trying the `shared_final_weights` option

`out = TimeDistributed(Dense(output_length ... `

that I changed to

`out = TimeDistributed(Dense(self.output_length ... `

And got the training started with:

```bash
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
Total model parameters: 7196
---current learning rate: 0.00100000
Epoch 1/1000
```

But then the following error happend then:

```python
Caused by op 'softmax/Reshape_1', defined at:
  File "nntimeseries/nnts/models/SOCNN.py", line 189, in <module>
    runner.run(SOCNNmodel, log=log, limit=6)
  File "nntimeseries/nnts/utils.py", line 150, in run
    model = model_class(data, params, os.path.join(WDIR, 'tensorboard'))
  File "nntimeseries/nnts/utils.py", line 263, in __init__
    self.nn, self.io_func, self.callbacks = self.build()
  File "nntimeseries/nnts/models/SOCNN.py", line 152, in build
    sig = TimeDistributed(Activation('softmax'), name='softmax')(sig)
  File "anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 578, in __call__
    output = self.call(inputs, **kwargs)
  File "anaconda3/lib/python3.6/site-packages/keras/layers/wrappers.py", line 180, in call
    y = K.reshape(y, (-1, input_length) + output_shape[2:])
  File "anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1568, in reshape
    return tf.reshape(x, shape)
  File "anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2630, in reshape
    name=name)
  File "anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[Node: softmax/Reshape_1 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](softmax/Softmax, softmax/Reshape_1/shape)]]
	 [[Node: add/_445 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_10390_add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

```

**Comment by xenmind** [comment]
Hi, Same problem after model is built:
`Traceback (most recent call last):   File "nnts/models/SOCNN.py", line 158, in <module>     runner.run(SOCNNmodel, log=log, limit=1)   File "C:\Users\xen\Desktop\nntimeseries-master\nnts\utils.py", line 153, in run     pd.DataFrame(self.cresults).to_pickle(self.save_file)   File "C:\Python36\lib\site-packages\pandas\core\generic.py", line 1378, in to_pickle     return to_pickle(self, path, compression=compression)   File "C:\Python36\lib\site-packages\pandas\io\pickle.py", line 27, in to_pickle     is_text=False)   File "C:\Python36\lib\site-packages\pandas\io\common.py", line 388, in _get_handle     f = open(path_or_buf, mode) FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xen\\Desktop\\nntimeseries-master\\results\\artificial_nnts/models/SOCNN.pkl'`

I also had an earlier problem about a log file not being at a particular location: ...\nntimeseries-master\logs\artificial_nnts\models\SOCNN08.10.17 which prevented anything from running. I create an empty txt file (which is now filled with log details) and directories and it worked afterwards, but ended in the above pickle file missing.
